
clean:
	rm -f -r objs *.o *.prx *.sym *.elf *.sprx *.a

all:
	# make clean
	rm -f -r objs *.o *.prx *.sym *.elf
	make -f Makefile.mak --no-print-directory
	rm -f -r objs *.o *.prx *.sym *.elf
	# make clean
